#---------------------------------------------------------------
# Theme version infromation
#---------------------------------------------------------------
version: 1.0

#---------------------------------------------------------------
# Build setting
#---------------------------------------------------------------
markdown: kramdown

gems: [jekyll-paginate]
# Config sass build output by sass_dir
# Config sass output is compressed or not
#
sass:
    sass_dir: /assets/stylesheet
    style: :compressed


#---------------------------------------------------------------
# Site infromation setting
#---------------------------------------------------------------

# Site
## You can create a locale setting at _locales and name *.yml
title: "Barisesen.com"
description: "Barış Esen Pamukkale Üniversitesi Bilgisayar Mühendisliği 2. sınıf öğrencisi. Web geliştiriciliği ve web uygulama güvenliğine ilgi duyuyorum."
keywords: "Barış Esen, Pamukkale Üniversitesi, Bilgisayar Mühendisi, NodeJs, Php, Code, web, mobil, linux, yazılım, siber güvenlik"
locale: "en"

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and baseurl as '/child/'
# url: "http://localhost:4000"
url: "https://barisesen.com"
baseurl: ""
permalink: /:title


# Pagination
## Set per_page to 0 to disable pagination
paginate: 5
paginate_path: /:num/


# Writing
# highlighter: 'pygments'
# kramdown:
#   input:  GFM
#   enable_coderay: false
#   coderay:
#     coderay_line_numbers:  nil

# RSS
rss:
  path: "/feed.xml"
  icon: "rss"


#---------------------------------------------------------------
# Authour infromation setting
#---------------------------------------------------------------

# Author
author:
  name: "Barış Esen"
  avatar: "https://res.cloudinary.com/deuit9vp2/image/upload/v1479924700/me.jpg"
  motto: "Pamukkale Üniversitesi Bilgisayar Mühendisliği 2. sınıf öğrencisi. Web geliştiriciliği ve web uygulama güvenliğine ilgi duyuyorum."

# Socials
## If you want the social show,place sure the social no comment
## The socials icon base font-awesome,you can learn more on http://fontawesome.io/icons/
socials:
    - name: "github"
      url: "https://github.com/barisesen"
      icon: "github"
    - name: "facebook"
      url: "https://www.facebook.com/brsesen"
      icon: "facebook"
    - name: "twitter"
      url: "https://www.twitter.com/barisesenn"
      icon: "twitter"
    - name: "linkedin"
      url: "https://tr.linkedin.com/in/barisesen"
      icon: "linkedin"




#---------------------------------------------------------------
# Site comment setting
#---------------------------------------------------------------

comment:
  enable: true

# duoshuo
duoshuo:
  enable: false
  short_name: "your duoshuo short_name"

# disqus
disqus:
  enable: true
  short_name: "barisesen"

#---------------------------------------------------------------
# Site share setting
#---------------------------------------------------------------
duoshuo_share:
    enable: false

#---------------------------------------------------------------
# Site analysis setting
#---------------------------------------------------------------
# Baidu analysis
baidu_analysis:
  enable: false
  token: "your baidu analysis token"

# Google analysis
google_analysis:
  enable: true
  token: "UA-76834314-1"
